FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update \
    # dependencies for building Python packages
    && apt-get install -y build-essential \
    # psycopg2 dependencies
    && apt-get install -y libpq-dev \
    # Additional dependencies
    && apt-get install -y telnet netcat \
    # cleaning up unused files
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && rm -rf /var/lib/apt/lists/*

# Requirements are installed here to ensure they will be cached.
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./docker/fastapi/start.sh /start
RUN sed -i 's/\r$//g' /start
RUN chmod +x /start

COPY ./docker/fastapi/alembic.sh /alembic
RUN sed -i 's/\r$//g' /alembic
RUN chmod +x /alembic

WORKDIR /app

ENTRYPOINT ["/start"]
